<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroFinance.Applicaiton\MicroFinance.Applicaiton.csproj" />
    <ProjectReference Include="..\MicroFinance.Domain\MicroFinance.Domain.csproj" />
    <ProjectReference Include="..\MicroFinance.Infrastructure\MicroFinance.Infrastructure.csproj" />
  </ItemGroup>

</Project>
